### ISSUE TITLE
伟大的hub主  15并不能用的呀

### ISSUE THREAD

**Issue by GitTigers** [kkzxak47/keycloak-services-social-wechatwork#16]
[org.keycloak.services.error.KeycloakErrorHandler] (default task-9) Uncaught server error: java.lang.NoClassDefFoundError: org/infinispan/configuration/cache/ConfigurationBuilder
        at org.keycloak.social.wechat.WechatWorkIdentityProvider.getCacheManager(WechatWorkIdentityProvider.java:88)
        at org.keycloak.social.wechat.WechatWorkIdentityProvider.get_cache(WechatWorkIdentityProvider.java:97)
        at org.keycloak.social.wechat.WechatWorkIdentityProvider.<clinit>(WechatWorkIdentityProvider.java:84)
        at org.keycloak.social.wechat.WechatWorkIdentityProviderFactory.create(WechatWorkIdentityProviderFactory.java:37)
        at org.keycloak.social.wechat.WechatWorkIdentityProviderFactory.create(WechatWorkIdentityProviderFactory.java:25)
        at org.keycloak.keycloak-services@15.0.0//org.keycloak.services.resources.IdentityBrokerService.performLogin(IdentityBrokerService.java:389)

**Comment by kkzxak47** [comment]
你试试。jar包路径改对。

> PS: 为了缓存企业微信的access_token，我直接使用了org.infinispan.Cache，因为Keycloak自己就使用了这个缓存组件，我就不用再增加依赖了。但最后还是遇到了依赖问题Uncaught server error: java.lang.NoClassDefFoundError: org/infinispan/configuration/cache/ConfigurationBuilder，原本在项目pom.xml里添加了org.infinispan只在编译时有效，最后部署时，还是要在KEYCLOAK_HOME/modules/system/layers/keycloak/org/keycloak/keycloak-services/main/module.xml里的dependencies里添加依赖，module.xml文件最后长这样：

`<module name="org.keycloak.keycloak-services" xmlns="urn:jboss:module:1.3">
    <properties>
        <property name="jboss.api" value="private"/>
    </properties>

    <resources>
        <resource-root path="keycloak-services-6.0.1.jar"/>
    </resources>

    <dependencies>
        <module name="org.infinispan" services="import"/>
        <module name="org.keycloak.keycloak-common" services="import"/>
    ...
    </dependencies>
</module>`

**Comment by GitTigers** [comment]
谢谢你  他是有效的
